# /.gitpod/.gitpod.yml (수정된 버전)

image: gitpod/workspace-full:latest

tasks:
  - name: Python API Server
    init: pip3 install -r python-service/requirements.txt
    # open 속성 제거!
    command: cd python-service && python3 app.py 

  - name: Java Client Service
    init: sudo apt update && sudo apt install -y openjdk-17-jdk maven
    # open 속성 제거!
    command: cd java-service && mvn clean install -DskipTests && java -jar target/your-java-app.jar

# ports 섹션에서 onOpen 속성을 사용하여 동작을 정의합니다.
ports:
  - port: 5000
    # 브라우저를 자동으로 열지 않도록 'ignore'로 설정합니다. (내부 통신용)
    onOpen: ignore
  - port: 8080
    # 브라우저를 자동으로 열지 않도록 'ignore'로 설정합니다. (내부 통신용)
    onOpen: ignore
