# .gitpod.yml: Gitpod 환경 설정 파일

# 1. 환경 이미지 설정
# 자바와 파이썬을 모두 지원하는 범용적인 이미지를 사용합니다.
image: gitpod/workspace-full:latest

# 2. 작업(Tasks) 정의
# 두 개의 독립적인 터미널과 실행 명령을 정의합니다.
tasks:
  # 파이썬 REST API 서버 설정
  - name: Python API Server
    # 초기화: 필요한 파이썬 라이브러리 설치
    init: pip install -r python-service/requirements.txt
    # 실행: Flask/FastAPI 서버를 5000 포트로 백그라운드에서 실행
    command: cd python-service && python app.py
    open: '5000' # 포트 설정

  # 자바 클라이언트 서비스 설정
  - name: Java Client Service
    # 초기화: Java 17 및 Maven 설치
    init: sudo apt update && sudo apt install -y openjdk-17-jdk maven
    # 실행: 자바 서비스 빌드 및 실행 (토이 프로젝트의 실제 실행 명령어에 맞게 수정 필요)
    # 예시: mvn install 후, JAR 파일을 실행하는 명령
    command: cd java-service && mvn clean install -DskipTests && java -jar target/your-java-app.jar
    open: '8080' # Spring Boot 등 사용 시 포트 설정

# 3. 포트(Ports) 정의
# 워크스페이스 내에서 포트가 어떻게 처리될지 정의합니다.
ports:
  - port: 5000
    onOpen: ignore   # 파이썬 포트. 내부 통신용이므로 브라우저 자동 열림 방지
  - port: 8080
    onOpen: ignore   # 자바 포트. 내부 통신용
